frames:
  - name: 'link_1'
    spheres:
      - pos: [0.11, -0.4657, 0.42]
        radius: 0.06
      - pos: [0.11, -0.4657, 0.3]
        radius: 0.06
      - pos: [0.11, -0.4657, 0.18]
        radius: 0.06
      - pos: [0.11, -0.4657, 0.06]
        radius: 0.06
      - pos: [-0.02, -0.4657, 0.42]
        radius: 0.06
      - pos: [-0.02, -0.4657, 0.3]
        radius: 0.06
      - pos: [-0.02, -0.4657, 0.18]
        radius: 0.06
      - pos: [-0.02, -0.4657, 0.06]
        radius: 0.06
      - pos: [ 0.045, -0.4657, 0.42 ]
        radius: 0.06
      - pos: [ 0.045, -0.4657, 0.3 ]
        radius: 0.06
      - pos: [ 0.045, -0.4657, 0.18 ]
        radius: 0.06
      - pos: [ 0.045, -0.4657, 0.06 ]
        radius: 0.06

      - pos: [ 0.11, -0.5307, 0.42 ]
        radius: 0.06
      - pos: [ 0.11, -0.5307, 0.3 ]
        radius: 0.06
      - pos: [ 0.11, -0.5307, 0.18 ]
        radius: 0.06
      - pos: [ 0.11, -0.5307, 0.06 ]
        radius: 0.06
      - pos: [ -0.02, -0.5307, 0.42 ]
        radius: 0.06
      - pos: [ -0.02, -0.5307, 0.3 ]
        radius: 0.06
      - pos: [ -0.02, -0.5307, 0.18 ]
        radius: 0.06
      - pos: [ -0.02, -0.5307, 0.06 ]
        radius: 0.06
      - pos: [ 0.045, -0.5307, 0.42 ]
        radius: 0.06
      - pos: [ 0.045, -0.5307, 0.3 ]
        radius: 0.06
      - pos: [ 0.045, -0.5307, 0.18 ]
        radius: 0.06
      - pos: [ 0.045, -0.5307, 0.06 ]
        radius: 0.06

      - pos: [ 0.11, -0.5957, 0.42 ]
        radius: 0.06
      - pos: [ 0.11, -0.5957, 0.3 ]
        radius: 0.06
      - pos: [ 0.11, -0.5957, 0.18 ]
        radius: 0.06
      - pos: [ 0.11, -0.5957, 0.06 ]
        radius: 0.06
      - pos: [ -0.02, -0.5957, 0.42 ]
        radius: 0.06
      - pos: [ -0.02, -0.5957, 0.3 ]
        radius: 0.06
      - pos: [ -0.02, -0.5957, 0.18 ]
        radius: 0.06
      - pos: [ -0.02, -0.5957, 0.06 ]
        radius: 0.06
      - pos: [ 0.045, -0.5957, 0.42 ]
        radius: 0.06
      - pos: [ 0.045, -0.5957, 0.3 ]
        radius: 0.06
      - pos: [ 0.045, -0.5957, 0.18 ]
        radius: 0.06
      - pos: [ 0.045, -0.5957, 0.06 ]
        radius: 0.06
        # left to right, front to back, top to bottom
