frames:
  - name: 'link_1'
    spheres:
      - pos: [ 0.03, 0.03, 0.15 ]
        radius: 0.03
      - pos: [ 0.02, 0.02, 0.18 ]
        radius: 0.03
      - pos: [ 0.015, 0.015, 0.22 ]
        radius: 0.03
      - pos: [ -0.03, -0.03, 0.15 ]
        radius: 0.03
      - pos: [ -0.02, -0.02, 0.18 ]
        radius: 0.03
      - pos: [ -0.015, -0.015, 0.22 ]
        radius: 0.03
      - pos: [ 0, 0, 0.245 ]
        radius: 0.026
      - pos: [ 0, 0, 0.265 ]
        radius: 0.026
      - pos: [ 0, 0, 0.28 ]
        radius: 0.022
      - pos: [ 0, 0, 0.298 ]
        radius: 0.022

