frames:
  - name: 'iiwa_link_1'
    spheres:
      - pos: [0, 0, -0.1]
        radius: 0.13
      - pos: [0, 0, 0.03]
        radius: 0.1
      - pos: [0, -0.04, 0.07]
        radius: 0.1
      - pos: [0, -0.04, 0.17]
        radius: 0.1
  - name: 'iiwa_link_2' # x,z,y
    spheres:
      - pos: [0, -0.05, 0.06]
        radius: 0.1
      - pos: [0, 0.05, 0.04]
        radius: 0.1
      - pos: [0, 0.1, 0]
        radius: 0.1
  - name: 'iiwa_link_3'
    spheres:
      - pos: [0, 0, 0]
        radius: 0.08
      - pos: [0, 0.03, 0.1]
        radius: 0.08
      - pos: [0, 0.05, 0.22]
        radius: 0.08
  - name: 'iiwa_link_4'
    spheres:
      - pos: [0, 0, 0.06]
        radius: 0.08
      - pos: [0, 0.07, 0.03]
        radius: 0.08
      - pos: [0, 0.17, 0]
        radius: 0.08
  - name: 'iiwa_link_5'
    spheres:
      - pos: [0, 0, 0.05]
        radius: 0.07
      - pos: [0, 0.05, 0.08]
        radius: 0.07
      - pos: [0, 0.07, 0.2]
        radius: 0.07
  - name: 'iiwa_link_6' # x,z,y
    spheres:
      - pos: [0, -0.01, 0]
        radius: 0.08
      - pos: [0, 0.06, 0]
        radius: 0.06