frames:
  - name: 'link_1'
    spheres:
      - pos: [ 0.04, 0.04, 0.15 ]
        radius: 0.03
      - pos: [ 0.03, 0.03, 0.16 ]
        radius: 0.03
      - pos: [ 0.045, 0.045, 0.18 ]
        radius: 0.03
      - pos: [ 0.057, 0.057, 0.205 ]
        radius: 0.025
      - pos: [ 0.053, 0.053, 0.22 ]
        radius: 0.02
      - pos: [ 0.05, 0.05, 0.24 ]
        radius: 0.02
      - pos: [ 0.05, 0.05, 0.26 ]
        radius: 0.02
      - pos: [ 0.05, 0.05, 0.277 ]
        radius: 0.02
      - pos: [ -0.04, -0.04, 0.15 ]
        radius: 0.03
      - pos: [ -0.03, -0.03, 0.16 ]
        radius: 0.03
      - pos: [ -0.045, -0.045, 0.18 ]
        radius: 0.03
      - pos: [ -0.057, -0.057, 0.205 ]
        radius: 0.025
      - pos: [ -0.053, -0.053, 0.22 ]
        radius: 0.02
      - pos: [ -0.05, -0.05, 0.24 ]
        radius: 0.02
      - pos: [ -0.05, -0.05, 0.26 ]
        radius: 0.02
      - pos: [ -0.05, -0.05, 0.277 ]
        radius: 0.02
