frames:
  - name: 'shoulder_link'
    spheres:
      - pos: [ 0, 0, 0 ]
        radius: 0.1
  - name: 'upper_arm_link'
    spheres:
      - pos: [0, 0, 0.13]
        radius: 0.1
      - pos: [-0.1, 0, 0.138]
        radius: 0.07
      - pos: [-0.2, 0, 0.138]
        radius: 0.07
      - pos: [-0.3, 0, 0.138]
        radius: 0.07
      - pos: [-0.42, 0, 0.138]
        radius: 0.09
  - name: 'forearm_link'
    spheres:
      - pos: [ 0, 0, 0.06 ]
        radius: 0.06
      - pos: [ 0, 0, 0.05 ]
        radius: 0.057
      - pos: [ -0.01, 0, 0.04 ]
        radius: 0.055
      - pos: [ -0.035, 0, 0.017 ]
        radius: 0.045
      - pos: [ -0.07, 0, 0.017 ]
        radius: 0.045
      - pos: [ -0.105, 0, 0.017 ]
        radius: 0.045
      - pos: [ -0.14, 0, 0.017 ]
        radius: 0.045
      - pos: [ -0.175, 0, 0.017 ]
        radius: 0.045
      - pos: [ -0.21, 0, 0.017 ]
        radius: 0.045
      - pos: [ -0.245, 0, 0.017 ]
        radius: 0.045
      - pos: [ -0.28, 0, 0.017 ]
        radius: 0.045
      - pos: [ -0.315, 0, 0.017 ]
        radius: 0.045
      - pos: [ -0.35, 0, 0.017 ]
        radius: 0.045
      - pos: [ -0.39, 0, -0.009 ]
        radius: 0.045
      - pos: [ -0.39, 0, 0.03 ]
        radius: 0.045
  - name: 'wrist_1_link'
    spheres:
      - pos: [ 0, 0, -0.0045 ]
        radius: 0.0647
  - name: 'wrist_2_link'
    spheres:
      - pos: [0, -0.025, -0.0028]
        radius: 0.0445
      - pos: [0, -0.02, 0]
        radius: 0.044
      - pos: [0, 0, 0]
        radius: 0.044
      - pos: [0, 0.02, 0]
        radius: 0.044
      - pos: [0, 0.003, -0.018]
        radius: 0.044
  - name: 'wrist_3_link'
    spheres:
      - pos: [ 0, 0, -0.03 ]
        radius: 0.045
  - name: flange_interface
    spheres:
      - pos: [0.02, 0, 0]
        radius: 0.065
  - name: upper_ft_interface
    spheres:
      - pos: [0, 0 ,0]
        radius: 0.065
  - name: robotiq_arg2f_base_link
    spheres:
      - pos: [0, 0, 0.04]
        radius: 0.04
      - pos: [0, 0, 0.1]
        radius: 0.06
      - pos: [0, 0.03, 0.1]
        radius: 0.06
      - pos: [0, -0.03, 0.1]
        radius: 0.06
#  - name: right_outer_knuckle
#    spheres:
#      - pos: [0, 0.012, -0.012]
#        radius: 0.026
#  - name: right_outer_finger
#    spheres: # shows up as y being z, and z being y (but inverted)
#      - pos: [0, 0, -0.06]
#        radius: 0.02
#      - pos: [0, -0.0025, -0.085]
#        radius: 0.02
#      - pos: [0, -0.005, -0.112]
#        radius: 0.02
#  - name: right_inner_finger
#    spheres:
#      - pos: [0, 0.087, -0.112]
#        radius: 0.022
#      - pos: [0, 0.11, -0.117]
#        radius: 0.011
#      - pos: [0, 0.122, -0.117]
#        radius: 0.011
#  - name: right_inner_knuckle
#    spheres:
#      - pos: [0, 0, 0]
#        radius: 0.026

